Add instructions for building and installing bleeding edge Unity Explorer
decaprime/VRising-Modding pull request #3
Opened 2023-05-24 20:49 UTC by eatdrinksleepcode

First try at adding some more dev-focused instructions to the wiki. If this is useful I can add more.

2023-05-24 20:52 UTC, eatdrinksleepcode commented on dev/resources.md
> +Gloomrot {: .label .label-green } Unity Explorer needs to be built from source and installed manually:
> Gloomrot {: .label .label-green }

The thought here was to show that something about the page was specific to the current experimental state that things are in because of the Gloomrot release, and that once things settle down it is likely to change...without having to add a lot of words to that effect. Particularly for existing mod devs, maybe this would be a helpful sign: "Hey, this is new/different." If you don't think it's useful, feel free to remove it.

I got the syntax from https://github.com/just-the-docs/just-the-docs/blob/main/docs/index-test.md#labels, but I don't have any way of testing how it looks.

2023-05-24 20:54 UTC, eatdrinksleepcode commented on dev/resources.md
> +2. Install the .NET 6 SDK via [manual download](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) or [winget](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60) (winget i
Obviously a lot more could be written here, but I just wanted to get something useful up quickly. Later I might add specific instructions for these two steps elsewhere and link to them here.

2023-05-24 20:57 UTC, eatdrinksleepcode commented on dev/resources.md
> +2. Copy all of the files in the `Release\Release\UnityExplorer.BepInEx.IL2CPP.CoreCLR` subdirectory to the BepInEx plugin directory at `<steamapps>\common\VRising\BepInEx\plugins`.
I only actually needed to copy four dlls:

- mcs.dll
- Tomlet.dll
- UnityExplorer.BIE.IL2CPP.CoreCLR.dll
- UniverseLib.IL2CPP.Interop.dll

(Although I had some crashes, which could in theory be because runtime dlls were missing.)

But I figured for "getting started" instructions it was just easier to say "copy all files". The only harm it might do is if some other plugin they already have installed has a different version of one of those files; but that is an issue bigger than just this one plugin.

2023-05-24 21:30 UTC, decaprime requested changes

2023-05-24 21:39 UTC, merged

2023-05-24 21:40 UTC, decaprime commented
Sory @eatdrinksleepcode , got a bit confused trying some of the new GitHub web UIs and didn't meant to thrash around. It's a great contribution. Apologies for the overhead.

2023-05-25 02:04 UTC, eatdrinksleepcode commented
> Sory @eatdrinksleepcode , got a bit confused trying some of the new GitHub web UIs and didn't meant to thrash around. It's a great contribution. Apologies for the overhead.

No problem at all! Happy to help. I'll see what else I can add.